name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel \
            build-essential libffi-dev libssl-dev liblzma-dev \
            libjpeg-dev libfreetype6-dev libgl1-mesa-dev \
            libgles2-mesa-dev unzip openjdk-17-jdk \
            zlib1g-dev libncurses5 git wget

      - name: Upgrade pip & install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade Cython
          pip install kivy buildozer requests beautifulsoup4

      - name: Initialize Buildozer
        run: |
          cd project
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Prepare Android SDK & NDK
        run: |
          cd project
          yes | buildozer android accept_sdk_license

      - name: Build APK
        run: |
          cd project
          export PATH=$PATH:~/.buildozer/android/platform/android-sdk/platform-tools
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FutureSignals-APK
          path: project/bin/*.apk
